In [2]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [4]:
df = datasets.load_iris(as_frame=True).frame

In [5]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [9]:
df.isnull().sum()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

(150, 5)

In [10]:
X= df.drop("target", axis = 1)
y = df["target"]

In [11]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [14]:
X_train,X_test,y_train,y_test =  train_test_split(
    X,y,test_size = 0.3,random_state=42,stratify = y)

In [16]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
#  Model
svc = SVC()
svc.fit(X_train_scaled,y_train)

SVC()

In [19]:
y_pred = svc.predict(X_test_scaled)

In [20]:
# evaluation
from sklearn.metrics import accuracy_score , classification_report
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("classification_report:",classification_report(y_test,y_pred))

accuracy_score: 0.9333333333333333
classification_report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [21]:
#  linear kernel ke liye 
svc = SVC(kernel="linear")
svc.fit(X_train_scaled,y_train)
y_pred = svc.predict(X_test_scaled)
print("accuracy_score:",accuracy_score(y_test,y_pred))

accuracy_score: 0.9111111111111111

In [23]:
#  for polynomial kernel check it out
svc = SVC(kernel="poly")
svc.fit(X_train_scaled,y_train)
y_pred = svc.predict(X_test_scaled)
print("accuracy_score:",accuracy_score(y_test,y_pred))
#

accuracy_score: 0.8666666666666667

In [24]:
#  sigmoid kernel
svc = SVC(kernel="sigmoid")
svc.fit(X_train_scaled,y_train)
y_pred = svc.predict(X_test_scaled)
print("accuracy_score:",accuracy_score(y_test,y_pred))

accuracy_score: 0.9111111111111111

In [26]:
C_vals = [0.5,1,2,3,4,5]

for c_val in C_vals:
    
    svc = SVC(C=c_val,kernel="rbf")
    svc.fit(X_train_scaled,y_train)
    y_pred = svc.predict(X_test_scaled)
    print("C = ",c_val,"&accuracy_score:",accuracy_score(y_test,y_pred))

C =  0.5 &accuracy_score: 0.9111111111111111
C =  1 &accuracy_score: 0.9333333333333333
C =  2 &accuracy_score: 0.9111111111111111
C =  3 &accuracy_score: 0.9111111111111111
C =  4 &accuracy_score: 0.9333333333333333
C =  5 &accuracy_score: 0.9333333333333333